### ISSUE TITLE
extension is not installable: missing executable

### ISSUE THREAD

**Issue by yermulnik** [gabe565/gh-profile#1]
```bash
> gh extension install gabe565/gh-profile
extension is not installable: missing executable

> gh version
gh version 2.17.0 (2022-10-04)
https://github.com/cli/cli/releases/tag/v2.17.0
```

**Comment by gabe565** [comment]
The v1.0.0 build is underway! Will be installable pretty soon.

**Comment by gabe565** [comment]
v1.0.0 is released! Try to install again.

**Comment by yermulnik** [comment]
Also would be great if `create` command asked for values for `oauth_token`, `git_protocol`, and `user` to eliminate the burden to manually edit `hosts.yml` for each newly created profile.

**Comment by gabe565** [comment]
Both are good points!

1. Completion is fully supported by gh-profile if installed as a standalone command, but I haven't been able to get it working as an extension yet. I'll update this issue if I'm able to make any progress!
2. `gh profile list` currently gives an overview of available profiles (and it prints a `*` before the active profile), but that's a good idea. I'll add a status subcommand!

**Comment by gabe565** [comment]
I should document the workflow a little better. I have been running `gh profile create`, then running `gh auth login` to run through the regular login workflow.

**Comment by yermulnik** [comment]
Thanks!
I have been using my [gist](https://gist.github.com/yermulnik/017837c01879ed3c7489cc7cf749ae47) to achieve the same functionality for a while now. I also added link to your repo in the very 1st comment so that others can utilize this extension too.
Looking forward for further development and would be happy to be of any use to help =)

**Comment by gabe565** [comment]
Oh thank you for linking to my repo! Your gist was only of my original inspirations for this extension :) I'll add a link to your gist too.

**Comment by yermulnik** [comment]
Sounds great. I have a will, though have no time to develop something more mauture myself =)

**Comment by gabe565** [comment]
I know the feeling. I luckily had some time and decided it would be worth it in this case.

Unfortunately, looks like shell completions aren't supported for gh extensions at the moment. See https://github.com/cli/cli/issues/5309

**Comment by yermulnik** [comment]
> Unfortunately, looks like shell completions aren't supported for gh extensions at the moment. See cli/cli#5309

That's odd 😢 Might worth to add instructions on how to install `gh-profile` as a standalone binary via `go install ...` or on how to add `~/.local/share/gh/extensions/gh-profile/gh-profile/` to `PATH` env var 🤔

**Comment by gabe565** [comment]
I'll go ahead and close this issue since builds are out and we have a separate issue for a status subcommand. Thank you!
